version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  up:
    desc: "Run application"
    cmds:
      - docker compose up --build

  setup:
    desc: "Setup application"
    cmds:
      - genenv .env.example

  buf/gen:
    desc: "Generate protobuf files"
    cmds:
      - buf lint proto
      - buf format --write proto
      - cd proto && buf generate --template ../server/buf.gen.yaml --output ../server

  go/check:
    desc: "Check Go code"
    dir: server
    cmds:
      - golangci-lint run --fix
      - golangci-lint fmt

  go/test:
    desc: "Test Go code"
    dir: server
    cmds:
      - go test -v -race ./...
