version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  up:
    desc: "Run application"
    cmds:
      - docker compose up --build -d

  down:
    desc: "Stop application"
    cmds:
      - docker compose down -v

  setup:
    desc: "Setup application"
    cmds:
      - genenv -y .env.example

  buf/gen:
    desc: "Generate protobuf files"
    dir: server
    cmds:
      - buf lint
      - buf format --write
      - buf generate

  go/check:
    desc: "Check Go code"
    dir: server
    cmds:
      - golangci-lint run --fix
      - golangci-lint fmt

  go/test:
    desc: "Test Go code"
    dir: server
    cmds:
      - go test -v -shuffle=on -race ./...

  db/schema/apply:
    desc: "Apply database schema using Atlas"
    dir: server
    cmds:
      - atlas schema apply --env docker --auto-approve

  db/schema/inspect:
    desc: "Inspect current database schema"
    dir: server
    cmds:
      - atlas schema inspect --env docker

  db/schema/diff:
    desc: "Show schema diff"
    dir: server
    cmds:
      - atlas schema diff --env docker

  db/sqlc/generate:
    desc: "Generate code from SQL queries using sqlc"
    dir: server
    cmds:
      - sqlc generate
