version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  run:
    desc: "Run application"
    cmds:
      - docker compose up --build

  buf/gen:
    desc: "Generate protobuf files"
    cmds:
      - buf lint
      - buf format --write
      - buf generate

  go/fmt:
    desc: "Format Go code"
    dir: server
    cmds:
      - go fmt ./...
      - goimports-reviser -rm-unused -set-alias -excludes gen -format ./...

  go/lint:
    desc: "Lint Go code"
    dir: server
    cmds:
      - golangci-lint run --fix
