// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/gemini/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/infra/gemini/client.go -destination=internal/service/gemini/mock_gemini_test.go -package=gemini_test
//

// Package gemini_test is a generated GoMock package.
package gemini_test

import (
	context "context"
	reflect "reflect"

	gemini "github.com/yashikota/scene-hunter/server/internal/infra/gemini"
	gomock "go.uber.org/mock/gomock"
)

// MockGemini is a mock of Gemini interface.
type MockGemini struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiMockRecorder
	isgomock struct{}
}

// MockGeminiMockRecorder is the mock recorder for MockGemini.
type MockGeminiMockRecorder struct {
	mock *MockGemini
}

// NewMockGemini creates a new mock instance.
func NewMockGemini(ctrl *gomock.Controller) *MockGemini {
	mock := &MockGemini{ctrl: ctrl}
	mock.recorder = &MockGeminiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGemini) EXPECT() *MockGeminiMockRecorder {
	return m.recorder
}

// AnalyzeImage mocks base method.
func (m *MockGemini) AnalyzeImage(ctx context.Context, imageData []byte, mimeType, prompt string) (*gemini.ImageAnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeImage", ctx, imageData, mimeType, prompt)
	ret0, _ := ret[0].(*gemini.ImageAnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeImage indicates an expected call of AnalyzeImage.
func (mr *MockGeminiMockRecorder) AnalyzeImage(ctx, imageData, mimeType, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeImage", reflect.TypeOf((*MockGemini)(nil).AnalyzeImage), ctx, imageData, mimeType, prompt)
}
