// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/blob/blob.go
//
// Generated by this command:
//
//	mockgen -source=internal/infra/blob/blob.go -destination=internal/service/gemini/mock_blob_test.go -package=gemini_test
//

// Package gemini_test is a generated GoMock package.
package gemini_test

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	blob "github.com/yashikota/scene-hunter/server/internal/infra/blob"
	gomock "go.uber.org/mock/gomock"
)

// MockBlob is a mock of Blob interface.
type MockBlob struct {
	ctrl     *gomock.Controller
	recorder *MockBlobMockRecorder
	isgomock struct{}
}

// MockBlobMockRecorder is the mock recorder for MockBlob.
type MockBlobMockRecorder struct {
	mock *MockBlob
}

// NewMockBlob creates a new mock instance.
func NewMockBlob(ctrl *gomock.Controller) *MockBlob {
	mock := &MockBlob{ctrl: ctrl}
	mock.recorder = &MockBlobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlob) EXPECT() *MockBlobMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBlob) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlobMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlob)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *MockBlob) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockBlobMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBlob)(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *MockBlob) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlobMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlob)(nil).Get), ctx, key)
}

// List mocks base method.
func (m *MockBlob) List(ctx context.Context, prefix string) ([]blob.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, prefix)
	ret0, _ := ret[0].([]blob.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBlobMockRecorder) List(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlob)(nil).List), ctx, prefix)
}

// Ping mocks base method.
func (m *MockBlob) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockBlobMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockBlob)(nil).Ping), ctx)
}

// Put mocks base method.
func (m *MockBlob) Put(ctx context.Context, key string, data io.Reader, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockBlobMockRecorder) Put(ctx, key, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBlob)(nil).Put), ctx, key, data, ttl)
}
