version: "2"
linters:
  default: all
  disable:
    - wsl
    - depguard
    - exhaustruct
    - mnd
  exclusions:
    generated: lax
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: lax
