name = "scene-hunter-game"
compatibility_date = "2025-05-12"

main = "src/index.ts"


# Durable Object の定義
[durable_objects]
bindings = [
  { name = "ROOM_OBJECT", class_name = "RoomObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomObject"]

[env.dev]
vars = { DEBUG = "true" }

# ローカルでの設定（HTTPポートやリスナーなど）
[dev]
port = 4282
local_protocol = "http"