// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRoom(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetRoomByCode(ctx context.Context, code string) (Room, error)
	GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error)
	GetUserByCode(ctx context.Context, code string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveRooms(ctx context.Context, expiredAt time.Time) ([]Room, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
