// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rooms.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    id,
    code,
    expired_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, expired_at, created_at, updated_at
`

type CreateRoomParams struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Code,
		arg.ExpiredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, code, expired_at, created_at, updated_at FROM rooms
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, code, expired_at, created_at, updated_at FROM rooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, code, expired_at, created_at, updated_at FROM rooms
WHERE expired_at > $1
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRooms(ctx context.Context, expiredAt time.Time) ([]Room, error) {
	rows, err := q.db.Query(ctx, listActiveRooms, expiredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, code, expired_at, created_at, updated_at FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
    code = $2,
    expired_at = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, code, expired_at, created_at, updated_at
`

type UpdateRoomParams struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	ExpiredAt time.Time `json:"expired_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Code,
		arg.ExpiredAt,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
