// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_identities.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (
    id,
    user_id,
    provider,
    subject,
    email,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, provider, subject, email, created_at
`

type CreateUserIdentityParams struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Provider  string      `json:"provider"`
	Subject   string      `json:"subject"`
	Email     pgtype.Text `json:"email"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.CreatedAt,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :exec
DELETE FROM user_identities
WHERE id = $1
`

func (q *Queries) DeleteUserIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserIdentity, id)
	return err
}

const getUserIdentitiesByUserID = `-- name: GetUserIdentitiesByUserID :many
SELECT id, user_id, provider, subject, email, created_at FROM user_identities
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, getUserIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdentityByID = `-- name: GetUserIdentityByID :one
SELECT id, user_id, provider, subject, email, created_at FROM user_identities
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserIdentityByID(ctx context.Context, id uuid.UUID) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByID, id)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdentityByProviderAndSubject = `-- name: GetUserIdentityByProviderAndSubject :one
SELECT id, user_id, provider, subject, email, created_at FROM user_identities
WHERE provider = $1 AND subject = $2
LIMIT 1
`

type GetUserIdentityByProviderAndSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserIdentityByProviderAndSubject(ctx context.Context, arg GetUserIdentityByProviderAndSubjectParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProviderAndSubject, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
