name: API

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v2-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v2-aqua-installer-${{runner.os}}-${{runner.arch}}-

      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.45.1

      - name: Setup tsp
        working-directory: api/spec
        run: pnpm install

      - name: Check
        run: task api/check

      - name: Compile
        run: task api/compile

      - name: Check for changes
        run: git diff --name-only --exit-code

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v2-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v2-aqua-installer-${{runner.os}}-${{runner.arch}}-

      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.45.1

      - name: Generate HTML documentation
        run: task api/doc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "api"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
